### ISSUE TITLE
Not Compatible After Updating to Debian Bullseye repositories

### ISSUE THREAD

**Issue by ebiscaia** [pimoroni/piglow#24]
Hi,

I'm having the following messages if I try to install Piglow
` curl https://get.pimoroni.com/piglow | bash                                                                                                                             ~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38667  100 38667    0     0  16468      0  0:00:02  0:00:02 --:--:-- 16482

This script will install everything needed to use
Piglow

Always be careful when running scripts and commands copied
from the internet. Ensure they are from a trusted source.

If you want to see what this script does before running it,
you should run: 'curl https://get.pimoroni.com/piglow'

--- Warning ---

The Piglow installer
does not work on this version of Raspbian.
Check https://github.com/pimoroni/piglow
for additional information and support
`
and 

` sudo apt-get install python3-piglow                                                                                                                                   ~
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-6+rpi1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
`

The problem occurs if you try to install Piglow after these chaanges:
`
edit the file /etc/apt/sources.list changing buster to bullseye;
 edit the file  /etc/apt/sources.list.d/raspi.list changing buster to bullseye;
sudo apt update; sudo apt upgrade -y
`

Thanks

**Comment by Gadgetoid** [comment]
I think your system package management is just broken, rather than a Piglow specific issue. You're not even getting to the point where the package is *trying* to install.

Granted the *first* error is intentional, to avoid installers running on releases we haven't tested. Although in most cases they should be fine. Bullseye is going to be a barrelful of fun, whee!

This issue - https://github.com/pimoroni/hyperpixel4/issues/149 - suggests you might have to run `sudo apt-get --allow-releaseinfo-change update` but I haven't got my systems into broken states often enough to know offhand how to fix it otherwise.

**Comment by ebiscaia** [comment]
Hi,

In the end I reinstalled the Raspberry Pi OS, then Piglow and last I updated the system changing the repository list.

Thanks,

Eduardo
